resources:
  # brew
  - type: package
    name: ansible
  - type: package
    name: caskroom/cask/brew-cask
#  - type: package
#    name: packer
#  - type: package
#    name: hub  # hub browse
#  - type: package
#    name: go
#  - type: package
#    name: mackup

  # brew cask
#  - type: homebrew_cask_package
#    name: alfred
#  - type: homebrew_cask_package
#    name: atom
  - type: homebrew_cask_package
    name: dropbox
#  - type: homebrew_cask_package
#    name: electron
#  - type: homebrew_cask_package
#    name: google-japanese-ime
#  - type: homebrew_cask_package
#    name: karabiner
#  - type: homebrew_cask_package
#    name: skitch
#  - type: homebrew_cask_package
#    name: slack
#  - type: homebrew_cask_package
#    name: vagrant
# - type: homebrew_cask_package
#    name: virtualbox
#  - type: homebrew_cask_package
#    name: visual-studio-code
  - type: homebrew_cask_package
    name: mounty

  # defaults
    type: defaults
    domain: com.apple.finder
    key: ShowStatusBar
    value: 1
  - id: ShowPath_finder # タイトルバーにパスを表示
    type: defaults
    domain: com.apple.finder
    key: _FXShowPosixPathInTitle
    value: 0
  - type: defaults
    domain: com.apple.dock
    key: magnification
    value: 1
    notify:
      - killall_Dock
  - type: defaults
    domain: com.apple.dock
    key: largesize
    value: 100
    notify:
      - killall_Dock
  - type: defaults
    domain: com.apple.Terminal
    key: Default Window Settings
    value: Basic2
  - type: defaults
    domain: com.apple.Terminal
    key: Startup Window Settings
    value: Basic2
  - type: defaults
    key: InitialKeyRepeat
    value: 15
  - type: defaults
    key: KeyRepeat
    value: 2
    notify:
      - killall_Safari

  # command
  - type: command
    check_script: defaults find orientation | grep left
    script: defaults write "com.apple.dock" "orientation" -string "left"
    notiry:
      - killall_Dock
# New windows points to home (finder)
  - type: command
    check_script: defaults find NewWindowTarget | grep PfHm
    script: defaults write com.apple.finder NewWindowTarget -string "PfHm"
  - type: command
    script: sudo defaults write /Library/Preferences/com.apple.alf globalstate -int 1
#  - type: command
#    script: defaults write -g com.apple.trackpad.scaling -float 2.0

# Three finger drag on
  - type: command
    check_script: defaults find TrackpadThreeFingerDrag | grep 1
    script: defaults write com.apple.AppleMultitouchTrackpad TrackpadThreeFingerDrag -bool true
  - type: command
    check_script: defaults find TrackpadThreeFingerDrag | grep 1
    script: defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadThreeFingerDrag -bool true


# Set `${HOME}` as the default location for new Finder windows
# 新しいウィンドウでデフォルトでホームフォルダを開く
#  - type: command
#    script: defaults write com.apple.finder NewWindowTarget -string "PfDe"
#  - type: command
#    script: defaults write com.apple.finder NewWindowTargetPath -string "file://${HOME}/"
#  - type: command
#    script: killall Finder

#  - type: karabiner
#    key: remap.jis_shiftSpace2toggle_kana_eisuu
#    value: 1
#    recheck_script: "true"
#  - type: karabiner
#    key: repeat.initial_wait
#    value: 200
#    recheck_script: "true"
#  - type: karabiner
#    key: repeat.wait
#    value: 30
#    recheck_script: "true"

#  - type: line
#    path: /etc/sudoers
#    pattern: 'hiroyuki +ALL=\(ALL\) NOPASSWD: ALL'
#    line: "hiroyuki ALL=(ALL) NOPASSWD: ALL"
#    insert_before: "^#includedir"
#    validation_script: visudo -cf %{path}

# NeoBundle (easy-motion)
  - type: git
    path: /Users/hiroyuki/.vim/bundle/neobundle.vim
    repository: https://github.com/Shougo/neobundle.vim
    state: updated
# dotfiles
  - type: git
    path: /Users/hiroyuki/github/dotfiles
    repository: https://github.com/hiroyuki12/dotfiles.git
    state: updated

  ## Apple Script
# set Tap to click on
  - type: command
    check_script: defaults find Clicking | grep 1
    script: osascript ~/github/dotfiles/appleScript/tapToClickOn.scpt

# change Dsiaplay Resolution
  - type: command
    script: osascript ~/github/dotfiles/appleScript/changeDisplayResolution.scpt

# show Favorites bar (safari)
  - type: command
    check_script: defaults find ShowFavoritesBar | grep 1
    script: osascript ~/github/dotfiles/appleScript/showFavoritesBar.scpt

# change caps lock to command
  - type: command
    script: osascript ~/github/dotfiles/appleScript/modifierKeyCapsLockToCommand.scpt

# change correct spelling off
  - type: command
    check_script: defaults find AutomaticSpellingCorrection | grep 0
    script: osascript ~/github/dotfiles/appleScript/CorrectSpellingOff.scpt

# ln .vimrc, .bash_profile, .gitconfig
  - type: symlink
    source: /Users/hiroyuki/.vimrc
    destination: /Users/hiroyuki/github/dotfiles/.vimrc
  - type: symlink
    source: /Users/hiroyuki/.bash_profile
    destination: /Users/hiroyuki/github/dotfiles/.bash_profile
  - type: symlink
    source: /Users/hiroyuki/.gitconfig
    destination: /Users/hiroyuki/github/dotfiles/.gitconfig

handlers:
  - id: killall_Finder
    type: command
    script: killall Finder
  - id: killall_Dock
    type: command
    script: killall Dock
  - id: killall_Safari
    type: command
    script: killall Safari

