resources:
  # brew
  - type: package
    name: ansible
  - type: package
    name: caskroom/cask/brew-cask
  - type: package
    name: packer


  # brew cask
  - type: homebrew_cask_package
    name: alfred
  - type: homebrew_cask_package
    name: atom
  - type: homebrew_cask_package
    name: dropbox
  - type: homebrew_cask_package
    name: electron
  - type: homebrew_cask_package
    name: google-japanese-ime
  - type: homebrew_cask_package
    name: karabiner
  - type: homebrew_cask_package
    name: kobito
  - type: homebrew_cask_package
    name: skitch
  - type: homebrew_cask_package
    name: slack
  - type: homebrew_cask_package
    name: vagrant
#  - type: homebrew_cask_package
#    name: virtualbox
#  - type: homebrew_cask_package
#    name: visual-studio-code

  # defaults
    type: defaults
    domain: com.apple.finder
    key: ShowStatusBar
    value: 1
  - id: Clicking_trackpad
#type: defaults
    type: defaults
    domain: com.apple.AppleMultitouchTrackpad
    key: Clicking
    value: 1
  - id: ShowPath_finder
    type: defaults
    domain: com.apple.finder
    key: _FXShowPosixPathInTitle
    value: 0
    notify:
      - killall_Finder
  - type: defaults
    domain: com.apple.dock
    key: magnification
    value: 1
    notify:
      - killall_Dock
  - type: defaults
    domain: com.apple.dock
    key: largesize
    value: 100
    notify:
      - killall_Dock

  # command
  - type: command
    script: defaults write "com.apple.dock" "orientation" -string "left"
    notiry:
      - killall_Dock
      
  - type: command
    script: sudo defaults write /Library/Preferences/com.apple.alf globalstate -int 1

# Set `${HOME}` as the default location for new Finder windows
# 新しいウィンドウでデフォルトでホームフォルダを開く
#  - type: command
#    script: defaults write com.apple.finder NewWindowTarget -string "PfDe"
#  - type: command
#    script: defaults write com.apple.finder NewWindowTargetPath -string "file://${HOME}/"
#  - type: command
#    script: killall Finder


  - type: karabiner
    key: repeat.wait
    value: 30 
    recheck_script: "true"

#  - type: line
  - type: nothing
    path: /etc/sudoers
    pattern: 'hiroyuki +ALL=\(ALL\) NOPASSWD: ALL'
    line: "hiroyuki ALL=(ALL) NOPASSWD: ALL"
    insert_before: "^#includedir"
    validation_script: visudo -cf %{path}

handlers:
  - id: killall_Finder
    type: command
    script: killall Finder
  - id: killall_Dock
    type: command
    script: killall Dock
